name: Sync SonarCloud Coverage information

on:
  workflow_dispatch: { }
  push:
    branches: [ "develop", "main" ]
    paths:
      - 'projects/**'
      - '.github/workflows/sync-sonar-coverage.yml'

jobs:

  get-branch:
    runs-on: ubuntu-latest
    env:
      REF_NAME: ${{ github.ref_name }}
    outputs:
      branch: ${{ steps.tag.outputs.tag }}
    steps:
      - id: tag
        run: |
          echo "branch=$REF_NAME" >> $GITHUB_OUTPUT


  update-python-projects-sonarcloud-coverage-report:
    needs: get-branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "authorizer", "sports", "sport-sessions", "users", "business-partners", "training-plans", "sport-events", "alerts", "nutritional-plans", "adverse-incidents", "adverse-incidents-provider" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        env:
          SERVICE: ${{ matrix.service }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry && poetry config virtualenvs.create false
          poetry install
          cd projects/$SERVICE && poetry install

      - name: Run unit tests and coverage
        env:
          SERVICE: ${{ matrix.service }}
        run: |
          cd projects/$SERVICE
          poetry run coverage run -m pytest
          poetry run coverage report -m --fail-under=75
          poetry run coverage xml

      - name: fix code coverage paths
        env:
          SERVICE: ${{ matrix.service }}
        run: |
          sed -i 's/\/home\/runner\/work\/sportapp-back\/sportapp-back\//\/github\/workspace\//g' projects/$SERVICE/coverage.xml

      - name: Add branch name to properties file
        env:
          SERVICE: ${{ matrix.service }}
          BRANCH: ${{ needs.get-branch.outputs.branch }}
        run: |
          echo "sonar.branch.name=$BRANCH" >> projects/$SERVICE/sonar-project.properties

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: projects/${{ matrix.service }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  update-js-projects-sonarcloud-coverage-report:
    needs: get-branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "miso-stripe" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Yarn
        run: |
          npm i -g yarn

      - name: Install dependencies
        env:
          SERVICE: ${{ matrix.service }}
        run: |
          cd projects/$SERVICE
          yarn install --frozen-lockfile

      - name: Run Unit tests and coverage
        env:
          SERVICE: ${{ matrix.service }}
        run: |
          cd projects/$SERVICE
          yarn test:unit

      - name: Add branch name to properties file
        env:
          SERVICE: ${{ matrix.service }}
          BRANCH: ${{ needs.get-branch.outputs.branch }}
        run: |
          echo "sonar.branch.name=$BRANCH" >> projects/$SERVICE/sonar-project.properties

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: projects/${{ matrix.service }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
